development: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: pros_development


test:
  <<: *default
  database: pros_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 15
